[credentials]
host = ''
dbname = ''
username = ''
password = ''

[qas]
'Monica Estrada' = 'Neurology, Neurosurgery, Neuro Operators'
'Daisy Colin' = 'Surgery'

'Eric Gaona' = """Transplant, Urgent Care, Hand and Wrist,
Plastics, Counselling, Orthopedics, Rheumatology"""

'Juan I. Recio' = 'Diabetes and Endocrinology'


